# 配置文件
backbone: mobilenetv2
pretrained: False
model_path: weights/mobilenet_v2-b0353104.pth
dataset: tinyimagenet
freeze_epoch: 10
freeze_batch_size: 128
all_epoch: 50
unfreeze_batch_size: 128
init_lr: 0.01
min_lr: 0.0001
num_workers: 4
optimizer: sgd
momentum: 0.9
weight_decay: 0.0005
lr_decay_type: cos
save_period: 10
weibull_threshold: 0.9

input_shape: 
  - 64
  - 64
